### ISSUE TITLE
Does this support failover?

### ISSUE THREAD

**Issue by patrykk21** [rocketjob/active_record_slave#11]
Hello, everyone,

Sorry for not following the format but this is a simple question that doesn't really fit into it.

Basically, what happens if one of the slave databases is unreachable for any reason? It will surely not fallback to another slave since you can only have one slave per instance, but would it fallback to master?

I think this information should be added to `README.md`.

LMK, thank you

Sorry if I created an issue for something that might not be one.

**Comment by reidmorrison** [comment]
There are no plans to support failover, since that kind of capability would have to be part of the Active Record drivers themselves to detect the failure condition and switch servers.
