### ISSUE TITLE
Can we use a better metaphor?

### ISSUE THREAD

**Issue by jbarrieault** [rocketjob/active_record_slave#12]
The Master/Slave terminology used by this gem is unnecessarily harsh, as well as insensitive to the human suffering brought about by slavery throughout the world (past and present). I think we can do better. 🙂

Would you be open to renaming the gem using different, less brutal terms? Perhaps Primary/Replica, or Primary/Reader, etc.?

I'm happy to submit a PR and help in any other way. 

Here's a fork exploring the idea: https://github.com/jbarrieault/active_record_reader

**Comment by reidmorrison** [comment]
The terminology was not invented here, it just follows the existing naming currently used by the relational databases themselves.

https://dev.mysql.com/doc/refman/5.7/en/replication-setup-slaves.html
