### ISSUE TITLE
Multiple databases

### ISSUE THREAD

**Issue by mainameiz** [rocketjob/active_record_slave#16]
Consider there is a model like this:

```ruby
class DifferentStorage::Base < ActiveRecord::Base
  establish_connection(YAML.load(File.read('config/database.yml')))["different_storage_#{Rails.env}"])

  self.abstract_class = true
end
```

### Expected Behavior

I expect that read queries for that model will be executed against different database (not master or slave). As well as for all child models.

### Actual Behavior

Read queries for that model are executed on slave database, which does not contain these models.
Update/delete queries are executed against right database, which constains these models.

---

Do you have a plan to support models which are stored in different database?

**Comment by reidmorrison** [comment]
Currently this gem does everything we need from need it in production. Supporting other databases would be a great idea. I will gladly accept a pull request if you add this capability.

**Comment by mainameiz** [comment]
:ok_hand:  I will make a PR

**Comment by mainameiz** [comment]
FYI Rails 6 will support database replicas out of the box https://github.com/rails/rails/pull/34052

**Comment by mainameiz** [comment]
I'm not going to make a PR. Sorry.
If you use mysql/mariadb you can look at temporary workaround in https://github.com/mainameiz/active_record_slave/pull/1 (until upgrade to Rails 6).
