### ISSUE TITLE
Read from Master as default doesn't work in Puma

### ISSUE THREAD

**Issue by abelorian** [rocketjob/active_record_slave#19]
Rails: 4.2.11.1
Puma: 3.6.2
Active_record_slave: 1.5.0

I think Thread.current.thread_variable_get(:active_record_slave) fail in puma cluster.

I set ActiveRecordSlave.read_from_master! in an initializer but 'reads' go to slave instead by default

**Comment by reidmorrison** [comment]
Correct, `ActiveRecordSlave.read_from_master!` only applies to the current thread and is _not_ a global setting across all threads. See https://github.com/rocketjob/active_record_slave/issues/20
