### ISSUE TITLE
Using it with postgresql_cursor hits master

### ISSUE THREAD

**Issue by jnylen** [rocketjob/active_record_slave#6]
Hi,
Using this with https://github.com/afair/postgresql_cursor makes it hit master.

@reidmorrison, any idea for a fix?

**Comment by jnylen** [comment]
Multiple `fetch 1000 from cursor_a45e504da1bf444ca6c225f9367293d4` calls on master.

**Comment by reidmorrison** [comment]
The code for this gem is really small. It only intercepts the following Active Record calls:
~~~ruby
:select, :select_all, :select_one, :select_rows, :select_value, :select_values
~~~

The place to look is to find out what method the gem above is using and either intercept that, or change the above gem to use one of the above queries.

Good Luck.
