### ISSUE TITLE
INSERT error into Slave when using Activerecord-Import

### ISSUE THREAD

**Issue by tmlee** [rocketjob/active_record_slave#7]
Using this gem alongside with https://github.com/zdennis/activerecord-import/

When calling
```
Model.import(some_data)
```

Got the following error
```
ActiveRecord::StatementInvalid: PG::ReadOnlySqlTransaction: ERROR:  cannot execute INSERT in a read-only transaction
```

Current workaround is to wrap the command with `ActiveRecordSlave.read_from_master` but ideally should just work out of the box

**Comment by reidmorrison** [comment]
The code for this gem is really small. It only intercepts the following Active Record calls:
~~~ruby
:select, :select_all, :select_one, :select_rows, :select_value, :select_values
~~~

The place to look is to find out what method the gem above is using and either intercept that, or change the above gem to use one of the above queries.

Good Luck.

**Comment by tmlee** [comment]
Thanks!
