### ISSUE TITLE
Is it possible to by default read/write from master db and on specific condition it reads from slave?

### ISSUE THREAD

**Issue by aliahmed922** [rocketjob/active_record_slave#8]
I have a big code base in which every query read/writes is executed against Master DB. Now I want (On some specific areas) to read only from Slave DB. This gem seems very useful for my case but by defaults it reads from slave and writes in master. I want this default behavior turn off and force a read against slave on specific active record query.

may be something like

`ActiveRecordSlave.read_from_slave do`
    `@users = User.count`
`end`

Is this possible?

**Comment by abelorian** [comment]
@aliahmed92 read_from_master as default, works for you? Dosn't work for me with v1.5.0 :(

**Comment by chaitali-railsfactory** [comment]
@abelorian read_from_master as default is not working for me too. Did you find any solution for this?
